name: Build and Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install and setup node
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Node Packages
        run: npm install

      # Build using angular
      - name: Build using Angular
        run: ng build --output-path dist --base-href /prompt-engineer/

      # Create artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: webpage
          path: dist
  
  # Deploy
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: webpage
          path: dist
      - name: Push to GitHub Pages branch
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: public
          github_token: ${{ secrets.GITHUB_TOKEN }}
