name: Build and Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install and setup node
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Node Packages
        run: npm install

      # Build using angular
      - name: Build using Angular
        run: npx ng build --output-path dist --base-href /prompt-engineer/

      # Create artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: github-pages
          path: dist

  # Deploy
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
